Repository intel/libva, pull requests merged in 2019-05, with the labels that each got.

#284 Add newformat foucc defination
  va/va.h
Labels: P2

#289 va/va_trace: add trace support for VAEncMiscParameterEncQuality
  va/va_trace.c
Labels: P3

#290 add return value into logs
  va/va.c
  va/va_str.c
  va/va_str.h
  va/va_trace.c
  va/va_trace.h
Labels: P2

#291 mark some duplicated field as deprecated
  va/va.h
Labels: P3

#267 va_openDriver: check strdup return value
  va/va.c
Labels: P3

#268 va/va_trace: add MPEG2 trace support for MiscParam and SequenceParam
  va/va_trace.c
Labels: P3

#288 va/va_trace: add trace support for VAEncMiscParameterTypeSkipFrame
  va/va_trace.c
Labels: P3

#256 Add definition for input/output surface flag
  va/va.h
  va/va_vpp.h
Labels: P2, help wanted
